// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ClientSessionProvider from "./ClientSessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* クライアントコンポーネントでセッションプロバイダーをラップする */}
        <ClientSessionProvider>{children}</ClientSessionProvider>
      </body>
    </html>
  );
}